insert into rooms values (1,2,1,3,500,'Cushion Wifi_5G coffee Morning');
insert into rooms values (2,3,0,4,1000,'Cushion Wifi_5G');
insert into rooms values (3,1,0,1,250,'Television Tea set Cushion');
insert into rooms values (4,4,3,5,4000,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (5,2,3,2,3000,'Cushion Television Speaker End_table Tea_set');
insert into rooms values (6,4,6,3,5000,'coffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (7,1,0,5,6000,'Tea set Fireplace coffee_Morning');
insert into rooms values (8,2,0,3,2000,'coffee Morning Wifi_5G');
insert into rooms values (9,3,1,2,1000,'Television Speaker');
insert into rooms values (9,3,2,2,5118,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (10,3,2,1,1666,'Wifi_5G');
insert into rooms values (11,4,4,5,679,'Cushion Wifi_5G coffee Morning');
insert into rooms values (12,3,2,4,9940,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (13,1,1,3,238,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (14,1,1,5,1313,'Tea set Fireplace coffee_Morning');
insert into rooms values (15,1,1,2,4165,'Tea set Fireplace coffee_Morning');
insert into rooms values (16,3,2,2,5679,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (17,2,2,3,7601,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (18,4,1,3,7783,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (19,1,2,1,3198,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (20,2,2,5,8529,'Cushion Wifi_5G coffee Morning');
insert into rooms values (21,1,3,4,4161,'Wifi_5G');
insert into rooms values (22,2,3,3,8567,'Tea set Fireplace coffee_Morning');
insert into rooms values (23,2,1,4,2518,'Tea set Fireplace coffee_Morning');
insert into rooms values (24,4,2,3,9538,'Tea set Fireplace coffee_Morning');
insert into rooms values (25,2,1,3,5263,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (26,1,2,5,582,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (27,2,1,5,6838,'Tea set Fireplace coffee_Morning');
insert into rooms values (28,4,4,3,3667,'Cushion Wifi_5G coffee Morning');
insert into rooms values (29,1,1,2,1964,'Cushion Wifi_5G coffee Morning');
insert into rooms values (30,4,1,3,9270,'Tea set Fireplace coffee_Morning');
insert into rooms values (31,1,4,3,9987,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (32,4,4,3,6682,'Wifi_5G');
insert into rooms values (33,4,3,4,3781,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (34,1,2,5,6923,'Cushion Wifi_5G coffee Morning');
insert into rooms values (35,4,1,2,985,'Cushion Wifi_5G coffee Morning');
insert into rooms values (36,1,2,4,3792,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (37,2,1,3,7915,'Tea set Fireplace coffee_Morning');
insert into rooms values (38,3,3,5,5314,'Cushion Wifi_5G coffee Morning');
insert into rooms values (39,1,2,1,6975,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (40,4,2,3,5007,'Tea set Fireplace coffee_Morning');
insert into rooms values (41,3,3,3,160,'Cushion Wifi_5G coffee Morning');
insert into rooms values (42,4,4,2,6397,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (43,2,1,1,9132,'Tea set Fireplace coffee_Morning');
insert into rooms values (44,1,3,1,8017,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (45,3,4,2,8715,'Wifi_5G');
insert into rooms values (46,2,1,1,1573,'Cushion Wifi_5G coffee Morning');
insert into rooms values (47,3,2,2,6690,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (48,2,2,5,6738,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (49,3,2,5,9097,'Wifi_5G');
insert into rooms values (50,2,1,3,9495,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (51,4,2,5,1315,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (52,4,2,3,205,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (53,4,1,2,5323,'Wifi_5G');
insert into rooms values (54,3,2,5,6777,'Wifi_5G');
insert into rooms values (55,1,2,4,593,'Wifi_5G');
insert into rooms values (56,1,1,2,1763,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (57,2,1,3,5494,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (58,4,3,4,2460,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (59,1,4,5,9961,'Wifi_5G');
insert into rooms values (60,3,3,4,8496,'Wifi_5G');
insert into rooms values (61,3,4,2,2371,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (62,3,2,5,6361,'Wifi_5G');
insert into rooms values (63,2,4,3,5214,'Cushion Wifi_5G coffee Morning');
insert into rooms values (64,1,3,5,524,'Wifi_5G');
insert into rooms values (65,1,4,3,8087,'Cushion Wifi_5G coffee Morning');
insert into rooms values (66,3,1,1,4492,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (67,4,2,2,9092,'Tea set Fireplace coffee_Morning');
insert into rooms values (68,4,1,5,479,'Cushion Wifi_5G coffee Morning');
insert into rooms values (69,3,4,3,1517,'Wifi_5G');
insert into rooms values (70,3,3,5,1550,'Tea set Fireplace coffee_Morning');
insert into rooms values (71,2,2,3,9799,'Tea set Fireplace coffee_Morning');
insert into rooms values (72,1,3,4,3476,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (73,1,1,4,4157,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (74,4,2,4,9603,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (75,4,2,3,2568,'Tea set Fireplace coffee_Morning');
insert into rooms values (76,3,1,1,9792,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (77,2,2,5,671,'Tea set Fireplace coffee_Morning');
insert into rooms values (78,4,4,4,292,'Cushion Wifi_5G coffee Morning');
insert into rooms values (79,4,2,5,8253,'Tea set Fireplace coffee_Morning');
insert into rooms values (80,3,4,4,8079,'Tea set Fireplace coffee_Morning');
insert into rooms values (81,4,2,1,9466,'Cushion Wifi_5G coffee Morning');
insert into rooms values (82,1,1,4,6416,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (83,1,3,2,7065,'Wifi_5G');
insert into rooms values (84,3,1,2,3105,'Wifi_5G');
insert into rooms values (85,2,1,4,5801,'Cushion Wifi_5G coffee Morning');
insert into rooms values (86,2,2,5,5991,'Wifi_5G');
insert into rooms values (87,2,1,4,2243,'Cushion Wifi_5G coffee Morning');
insert into rooms values (88,3,3,5,7527,'Cushion Wifi_5G coffee Morning');
insert into rooms values (89,3,4,2,1992,'Tea set Fireplace coffee_Morning');
insert into rooms values (90,1,4,2,467,'Tea set Fireplace coffee_Morning');
insert into rooms values (91,3,4,2,1724,'Tea set Fireplace coffee_Morning');
insert into rooms values (92,3,1,4,9334,'Cushion Wifi_5G coffee Morning');
insert into rooms values (93,3,3,4,835,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (94,1,4,1,1861,'Wifi_5G');
insert into rooms values (95,3,1,5,897,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (96,4,2,2,587,'Tea set Fireplace coffee_Morning');
insert into rooms values (97,3,2,4,540,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (98,1,3,2,886,'Tea set Fireplace coffee_Morning');
insert into rooms values (99,2,2,3,5216,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (100,2,2,1,1887,'Tea set Fireplace coffee_Morning');
insert into rooms values (101,1,2,5,8148,'Cushion Wifi_5G coffee Morning');
insert into rooms values (102,2,1,1,1541,'Tea set Fireplace coffee_Morning');
insert into rooms values (103,4,2,5,5084,'Tea set Fireplace coffee_Morning');
insert into rooms values (104,4,4,2,4387,'Wifi_5G');
insert into rooms values (105,2,2,4,9223,'Cushion Wifi_5G coffee Morning');
insert into rooms values (106,1,2,1,7376,'Tea set Fireplace coffee_Morning');
insert into rooms values (107,1,2,1,9013,'Wifi_5G');
insert into rooms values (108,4,3,4,1610,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (109,4,4,5,2087,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (110,4,1,2,1269,'Cushion Wifi_5G coffee Morning');
insert into rooms values (111,1,1,1,1176,'Wifi_5G');
insert into rooms values (112,2,2,5,3281,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (113,1,1,3,3637,'Cushion Wifi_5G coffee Morning');
insert into rooms values (114,4,4,5,956,'Cushion Wifi_5G coffee Morning');
insert into rooms values (115,1,1,3,8031,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (116,1,4,4,2577,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (117,3,3,2,4796,'Cushion Wifi_5G coffee Morning');
insert into rooms values (118,3,1,1,2393,'Tea set Fireplace coffee_Morning');
insert into rooms values (119,4,2,3,2425,'Tea set Fireplace coffee_Morning');
insert into rooms values (120,2,1,2,6183,'Cushion Wifi_5G coffee Morning');
insert into rooms values (121,3,4,1,8462,'Cushion Wifi_5G coffee Morning');
insert into rooms values (122,2,1,5,8043,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (123,3,1,4,5624,'Wifi_5G');
insert into rooms values (124,4,3,2,9925,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (125,2,4,2,1143,'Cushion Wifi_5G coffee Morning');
insert into rooms values (126,1,1,1,3290,'Wifi_5G');
insert into rooms values (127,3,4,3,4801,'Cushion Wifi_5G coffee Morning');
insert into rooms values (128,3,4,5,6948,'Cushion Wifi_5G coffee Morning');
insert into rooms values (129,1,2,3,5560,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (130,3,1,5,3661,'Tea set Fireplace coffee_Morning');
insert into rooms values (131,2,3,5,6313,'Cushion Wifi_5G coffee Morning');
insert into rooms values (132,1,1,1,6522,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (133,1,2,5,1202,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (134,1,3,4,6660,'Tea set Fireplace coffee_Morning');
insert into rooms values (135,1,1,2,6926,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (136,3,2,2,6622,'Cushion Wifi_5G coffee Morning');
insert into rooms values (137,1,2,3,9175,'Wifi_5G');
insert into rooms values (138,3,4,1,1341,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (139,3,1,2,5959,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (140,4,1,2,3388,'Tea set Fireplace coffee_Morning');
insert into rooms values (141,4,1,5,9662,'Tea set Fireplace coffee_Morning');
insert into rooms values (142,1,3,4,3211,'Wifi_5G');
insert into rooms values (143,1,2,2,753,'Wifi_5G');
insert into rooms values (144,3,4,3,1962,'Wifi_5G');
insert into rooms values (145,4,3,4,9523,'Cushion Wifi_5G coffee Morning');
insert into rooms values (146,1,3,3,9764,'Tea set Fireplace coffee_Morning');
insert into rooms values (147,4,4,1,5665,'Wifi_5G');
insert into rooms values (148,4,3,4,8556,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (149,3,3,5,2257,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (150,2,2,3,994,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (151,2,3,1,3816,'Cushion Wifi_5G coffee Morning');
insert into rooms values (152,4,4,2,3156,'Tea set Fireplace coffee_Morning');
insert into rooms values (153,1,3,4,470,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (154,1,4,2,9667,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (155,4,2,5,9778,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (156,1,1,4,8656,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (157,2,1,5,3544,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (158,4,3,1,2512,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (159,3,4,4,2510,'Cushion Wifi_5G coffee Morning');
insert into rooms values (160,2,2,5,4246,'Cushion Wifi_5G coffee Morning');
insert into rooms values (161,3,4,4,9103,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (162,2,2,4,3189,'Tea set Fireplace coffee_Morning');
insert into rooms values (163,3,4,5,7391,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (164,3,2,5,4463,'Tea set Fireplace coffee_Morning');
insert into rooms values (165,2,1,5,7156,'Cushion Wifi_5G coffee Morning');
insert into rooms values (166,3,2,2,9760,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (167,2,4,3,2870,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (168,3,1,1,7250,'Cushion Wifi_5G coffee Morning');
insert into rooms values (169,1,2,4,8060,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (170,1,4,5,4514,'Tea set Fireplace coffee_Morning');
insert into rooms values (171,3,3,4,1775,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (172,3,4,5,1697,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (173,1,1,4,4620,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (174,1,1,3,701,'Cushion Wifi_5G coffee Morning');
insert into rooms values (175,2,1,5,5008,'Cushion Wifi_5G coffee Morning');
insert into rooms values (176,3,3,3,2711,'Wifi_5G');
insert into rooms values (177,2,1,1,5899,'Tea set Fireplace coffee_Morning');
insert into rooms values (178,1,4,2,1824,'Tea set Fireplace coffee_Morning');
insert into rooms values (179,1,2,3,6568,'Wifi_5G');
insert into rooms values (180,1,1,1,8492,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (181,1,4,2,4767,'Cushion Wifi_5G coffee Morning');
insert into rooms values (182,1,4,2,5019,'Wifi_5G');
insert into rooms values (183,3,3,5,6665,'Cushion Wifi_5G coffee Morning');
insert into rooms values (184,3,3,2,5782,'Cushion Wifi_5G coffee Morning');
insert into rooms values (185,1,2,3,7031,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (186,2,2,4,7476,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (187,1,1,1,6633,'Cushion Wifi_5G coffee Morning');
insert into rooms values (188,2,1,3,9835,'Wifi_5G');
insert into rooms values (189,2,1,4,1651,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (190,2,3,3,6776,'Tea set Fireplace coffee_Morning');
insert into rooms values (191,2,3,1,7014,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (192,1,3,5,9338,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (193,1,4,2,5010,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (194,4,3,2,8480,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (195,3,3,3,9912,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (196,3,3,2,4930,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (197,2,3,4,9435,'Tea set Fireplace coffee_Morning');
insert into rooms values (198,3,4,2,5613,'Wifi_5G');
insert into rooms values (199,2,3,4,8120,'Cushion Wifi_5G coffee Morning');
insert into rooms values (200,2,4,2,9367,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (201,1,3,1,2741,'Cushion Wifi_5G coffee Morning');
insert into rooms values (202,3,3,1,4288,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (203,1,1,4,369,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (204,2,4,1,7940,'Cushion Wifi_5G coffee Morning');
insert into rooms values (205,4,4,4,2222,'Wifi_5G');
insert into rooms values (206,4,3,1,3067,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (207,3,2,3,4817,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (208,1,2,2,3189,'Wifi_5G');
insert into rooms values (209,1,4,4,7260,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (210,2,4,4,3261,'Tea set Fireplace coffee_Morning');
insert into rooms values (211,2,1,1,5447,'Wifi_5G');
insert into rooms values (212,1,1,3,8575,'Cushion Wifi_5G coffee Morning');
insert into rooms values (213,3,4,4,9590,'Wifi_5G');
insert into rooms values (214,1,4,5,7753,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (215,3,4,4,522,'Cushion Wifi_5G coffee Morning');
insert into rooms values (216,4,2,5,5108,'Cushion Wifi_5G coffee Morning');
insert into rooms values (217,4,1,5,9733,'Cushion Wifi_5G coffee Morning');
insert into rooms values (218,1,2,5,8127,'Tea set Fireplace coffee_Morning');
insert into rooms values (219,3,4,1,6807,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (220,4,4,2,3821,'Cushion Wifi_5G coffee Morning');
insert into rooms values (221,4,4,2,6337,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (222,3,3,2,8433,'Cushion Wifi_5G coffee Morning');
insert into rooms values (223,3,4,5,596,'Wifi_5G');
insert into rooms values (224,1,1,4,3127,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (225,1,2,5,2550,'Wifi_5G');
insert into rooms values (226,3,3,1,6731,'Wifi_5G');
insert into rooms values (227,4,2,5,6444,'Cushion Wifi_5G coffee Morning');
insert into rooms values (228,4,1,5,1642,'Cushion Wifi_5G coffee Morning');
insert into rooms values (229,1,1,1,5000,'Tea set Fireplace coffee_Morning');
insert into rooms values (230,1,4,1,3527,'Tea set Fireplace coffee_Morning');
insert into rooms values (231,4,2,4,7231,'Wifi_5G');
insert into rooms values (232,2,1,4,9201,'Wifi_5G');
insert into rooms values (233,4,1,3,3246,'Cushion Wifi_5G coffee Morning');
insert into rooms values (234,4,3,3,4919,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (235,2,1,3,7207,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (236,2,2,4,2136,'Wifi_5G');
insert into rooms values (237,3,2,2,4264,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (238,1,2,3,4410,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (239,3,2,2,827,'Cushion Wifi_5G coffee Morning');
insert into rooms values (240,1,4,1,5170,'Cushion Wifi_5G coffee Morning');
insert into rooms values (241,4,3,1,9189,'Wifi_5G');
insert into rooms values (242,3,1,4,5157,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (243,3,4,2,822,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (244,3,3,2,7903,'Cushion Wifi_5G coffee Morning');
insert into rooms values (245,2,4,5,161,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (246,4,4,3,8948,'Cushion Wifi_5G coffee Morning');
insert into rooms values (247,4,4,4,4033,'Tea set Fireplace coffee_Morning');
insert into rooms values (248,3,1,5,185,'Cushion Wifi_5G coffee Morning');
insert into rooms values (249,1,1,2,3359,'Tea set Fireplace coffee_Morning');
insert into rooms values (250,4,3,4,7399,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (251,1,2,3,4963,'Wifi_5G');
insert into rooms values (252,2,4,2,723,'Wifi_5G');
insert into rooms values (253,2,4,2,7494,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (254,4,2,1,5307,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (255,4,2,4,3584,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (256,2,2,5,7618,'Cushion Wifi_5G coffee Morning');
insert into rooms values (257,2,4,3,3120,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (258,1,4,4,6682,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (259,4,4,2,4206,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (260,1,1,5,9538,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (261,3,1,3,9494,'Cushion Wifi_5G coffee Morning');
insert into rooms values (262,3,4,2,5774,'Cushion Wifi_5G coffee Morning');
insert into rooms values (263,4,1,1,3345,'Tea set Fireplace coffee_Morning');
insert into rooms values (264,4,4,4,4966,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (265,1,3,3,3025,'Tea set Fireplace coffee_Morning');
insert into rooms values (266,4,4,1,1023,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (267,4,3,5,9641,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (268,1,4,4,1414,'Wifi_5G');
insert into rooms values (269,3,2,3,4364,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (270,1,1,4,8307,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (271,1,1,4,5943,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (272,4,3,4,7625,'Wifi_5G');
insert into rooms values (273,1,1,1,2617,'Wifi_5G');
insert into rooms values (274,4,2,5,9913,'Wifi_5G');
insert into rooms values (275,4,4,4,6202,'Wifi_5G');
insert into rooms values (276,2,2,1,6557,'Tea set Fireplace coffee_Morning');
insert into rooms values (277,2,3,2,6731,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (278,1,2,1,3466,'Tea set Fireplace coffee_Morning');
insert into rooms values (279,3,3,2,2596,'Cushion Wifi_5G coffee Morning');
insert into rooms values (280,4,4,4,8044,'Tea set Fireplace coffee_Morning');
insert into rooms values (281,1,1,1,953,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (282,4,2,5,4309,'Tea set Fireplace coffee_Morning');
insert into rooms values (283,2,2,1,6352,'Wifi_5G');
insert into rooms values (284,3,2,1,3103,'Tea set Fireplace coffee_Morning');
insert into rooms values (285,3,2,2,6106,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (286,3,2,1,6778,'Tea set Fireplace coffee_Morning');
insert into rooms values (287,4,1,1,7842,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (288,2,4,4,6068,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (289,2,2,2,6383,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (290,2,2,2,8460,'Wifi_5G');
insert into rooms values (291,4,4,1,2869,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (292,1,3,1,4917,'Tea set Fireplace coffee_Morning');
insert into rooms values (293,2,3,3,5160,'Tea set Fireplace coffee_Morning');
insert into rooms values (294,4,1,4,7601,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (295,1,1,2,6481,'Cushion Wifi_5G coffee Morning');
insert into rooms values (296,3,3,2,6540,'Tea set Fireplace coffee_Morning');
insert into rooms values (297,2,3,1,496,'Wifi_5G');
insert into rooms values (298,4,1,3,7698,'Cushion Wifi_5G coffee Morning');
insert into rooms values (299,1,2,3,1795,'Cushion Wifi_5G coffee Morning');
insert into rooms values (300,3,1,2,2460,'Tea set Fireplace coffee_Morning');
insert into rooms values (301,2,2,4,5469,'Wifi_5G');
insert into rooms values (302,3,1,2,2881,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (303,3,2,4,7197,'Cushion Wifi_5G coffee Morning');
insert into rooms values (304,1,2,1,4417,'Tea set Fireplace coffee_Morning');
insert into rooms values (305,4,3,3,3002,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (306,2,3,1,5815,'Tea set Fireplace coffee_Morning');
insert into rooms values (307,2,4,2,838,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (308,2,1,4,8928,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (309,1,4,1,4144,'Cushion Wifi_5G coffee Morning');
insert into rooms values (310,4,2,1,6277,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (311,4,4,5,6882,'Tea set Fireplace coffee_Morning');
insert into rooms values (312,1,1,5,433,'Tea set Fireplace coffee_Morning');
insert into rooms values (313,1,4,4,9505,'Cushion Wifi_5G coffee Morning');
insert into rooms values (314,3,4,2,6798,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (315,2,4,1,9877,'Tea set Fireplace coffee_Morning');
insert into rooms values (316,1,3,2,2850,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (317,1,3,3,9909,'Wifi_5G');
insert into rooms values (318,3,1,5,481,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (319,1,4,1,4352,'Wifi_5G');
insert into rooms values (320,1,2,5,9744,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (321,2,4,4,2320,'Tea set Fireplace coffee_Morning');
insert into rooms values (322,2,4,2,2816,'Tea set Fireplace coffee_Morning');
insert into rooms values (323,1,4,5,526,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (324,4,1,1,7556,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (325,3,2,1,2145,'Cushion Wifi_5G coffee Morning');
insert into rooms values (326,4,2,1,7941,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (327,4,2,1,8747,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (328,4,2,2,2512,'Tea set Fireplace coffee_Morning');
insert into rooms values (329,3,3,2,4663,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (330,1,1,5,8263,'Cushion Wifi_5G coffee Morning');
insert into rooms values (331,2,2,4,4866,'Tea set Fireplace coffee_Morning');
insert into rooms values (332,2,3,2,9875,'Cushion Wifi_5G coffee Morning');
insert into rooms values (333,2,1,3,4870,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (334,4,3,1,7163,'Cushion Wifi_5G coffee Morning');
insert into rooms values (335,2,2,5,8362,'Tea set Fireplace coffee_Morning');
insert into rooms values (336,3,2,3,5194,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (337,1,4,1,6563,'Tea set Fireplace coffee_Morning');
insert into rooms values (338,1,3,4,7681,'Tea set Fireplace coffee_Morning');
insert into rooms values (339,1,3,1,5100,'Tea set Fireplace coffee_Morning');
insert into rooms values (340,1,1,1,4654,'Wifi_5G');
insert into rooms values (341,1,4,3,8106,'Cushion Wifi_5G coffee Morning');
insert into rooms values (342,3,1,3,1470,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (343,3,4,1,7743,'Tea set Fireplace coffee_Morning');
insert into rooms values (344,1,2,2,3206,'Wifi_5G');
insert into rooms values (345,3,1,3,5680,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (346,2,4,4,6553,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (347,4,4,5,2759,'Tea set Fireplace coffee_Morning');
insert into rooms values (348,1,2,4,481,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (349,1,3,4,6748,'Wifi_5G');
insert into rooms values (350,4,2,5,7416,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (351,4,3,5,4570,'Wifi_5G');
insert into rooms values (352,4,2,4,1509,'Wifi_5G');
insert into rooms values (353,1,3,5,5874,'Wifi_5G');
insert into rooms values (354,4,2,2,2059,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (355,2,3,5,4309,'Cushion Wifi_5G coffee Morning');
insert into rooms values (356,2,4,5,7880,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (357,3,4,1,7663,'Cushion Wifi_5G coffee Morning');
insert into rooms values (358,4,2,5,7808,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (359,1,1,4,4495,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (360,4,2,2,7659,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (361,4,4,5,2331,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (362,3,4,2,9759,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (363,1,3,2,3641,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (364,4,2,5,4852,'Cushion Wifi_5G coffee Morning');
insert into rooms values (365,3,2,3,4204,'Tea set Fireplace coffee_Morning');
insert into rooms values (366,2,1,3,8644,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (367,4,3,3,9060,'Cushion Wifi_5G coffee Morning');
insert into rooms values (368,3,3,3,9191,'Cushion Wifi_5G coffee Morning');
insert into rooms values (369,4,3,5,1963,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (370,2,3,3,7527,'Cushion Wifi_5G coffee Morning');
insert into rooms values (371,3,1,1,9041,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (372,1,3,3,9241,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (373,2,4,1,7803,'Tea set Fireplace coffee_Morning');
insert into rooms values (374,2,1,5,5485,'Tea set Fireplace coffee_Morning');
insert into rooms values (375,1,4,1,5852,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (376,4,2,2,2308,'Wifi_5G');
insert into rooms values (377,3,2,1,1671,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (378,4,4,4,4590,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (379,3,3,1,4058,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (380,2,3,5,7675,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (381,3,2,2,9173,'Wifi_5G');
insert into rooms values (382,1,1,1,8410,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (383,2,2,1,9697,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (384,3,3,1,5100,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (385,1,3,5,7827,'Tea set Fireplace coffee_Morning');
insert into rooms values (386,3,3,4,2916,'Cushion Wifi_5G coffee Morning');
insert into rooms values (387,2,3,2,9725,'Tea set Fireplace coffee_Morning');
insert into rooms values (388,1,3,2,5611,'Tea set Fireplace coffee_Morning');
insert into rooms values (389,2,4,5,5198,'Tea set Fireplace coffee_Morning');
insert into rooms values (390,4,3,1,9648,'Cushion Wifi_5G coffee Morning');
insert into rooms values (391,2,3,1,2696,'Cushion Wifi_5G coffee Morning');
insert into rooms values (392,2,1,1,5583,'Tea set Fireplace coffee_Morning');
insert into rooms values (393,1,1,5,8235,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (394,3,4,3,2910,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (395,3,4,3,8969,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (396,1,1,2,1810,'Tea set Fireplace coffee_Morning');
insert into rooms values (397,2,1,4,1284,'Cushion Wifi_5G coffee Morning');
insert into rooms values (398,2,4,4,6929,'Cushion Wifi_5G coffee Morning');
insert into rooms values (399,3,4,3,2374,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (400,2,4,5,5324,'Tea set Fireplace coffee_Morning');
insert into rooms values (401,1,4,5,5923,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (402,2,2,3,8848,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (403,1,2,3,6596,'Wifi_5G');
insert into rooms values (404,3,2,3,1810,'Wifi_5G');
insert into rooms values (405,4,3,2,9562,'Cushion Wifi_5G coffee Morning');
insert into rooms values (406,1,3,3,863,'Tea set Fireplace coffee_Morning');
insert into rooms values (407,1,3,1,4509,'Tea set Fireplace coffee_Morning');
insert into rooms values (408,2,2,5,7380,'Wifi_5G');
insert into rooms values (409,2,3,4,4710,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (410,3,2,2,2890,'Tea set Fireplace coffee_Morning');
insert into rooms values (411,1,1,3,1256,'Tea set Fireplace coffee_Morning');
insert into rooms values (412,1,2,1,7764,'Tea set Fireplace coffee_Morning');
insert into rooms values (413,2,2,5,8586,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (414,3,3,5,7713,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (415,3,1,5,9462,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (416,4,3,5,4598,'Wifi_5G');
insert into rooms values (417,4,3,5,9397,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (418,2,4,3,8685,'Wifi_5G');
insert into rooms values (419,4,1,3,3131,'Tea set Fireplace coffee_Morning');
insert into rooms values (420,4,3,2,3636,'Cushion Wifi_5G coffee Morning');
insert into rooms values (421,3,2,4,333,'Wifi_5G');
insert into rooms values (422,1,1,2,2560,'Tea set Fireplace coffee_Morning');
insert into rooms values (423,2,2,3,781,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (424,4,1,1,2656,'Wifi_5G');
insert into rooms values (425,3,3,1,4596,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (426,2,1,1,7881,'Cushion Wifi_5G coffee Morning');
insert into rooms values (427,4,2,4,3842,'Cushion Wifi_5G coffee Morning');
insert into rooms values (428,2,4,1,2125,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (429,3,1,1,2362,'Tea set Fireplace coffee_Morning');
insert into rooms values (430,1,2,2,5187,'Tea set Fireplace coffee_Morning');
insert into rooms values (431,4,4,4,5057,'Tea set Fireplace coffee_Morning');
insert into rooms values (432,4,1,1,959,'Tea set Fireplace coffee_Morning');
insert into rooms values (433,3,1,5,2594,'Wifi_5G');
insert into rooms values (434,2,4,4,9193,'Tea set Fireplace coffee_Morning');
insert into rooms values (435,4,1,2,429,'Wifi_5G');
insert into rooms values (436,1,3,5,5777,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (437,4,3,1,2698,'Wifi_5G');
insert into rooms values (438,1,3,2,8197,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (439,1,3,1,2310,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (440,1,2,3,767,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (441,2,4,4,6624,'Wifi_5G');
insert into rooms values (442,1,4,5,956,'Cushion Wifi_5G coffee Morning');
insert into rooms values (443,3,4,5,4163,'Cushion Wifi_5G coffee Morning');
insert into rooms values (444,4,3,3,7879,'Cushion Wifi_5G coffee Morning');
insert into rooms values (445,1,3,3,7257,'Wifi_5G');
insert into rooms values (446,4,1,4,6403,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (447,2,2,3,8393,'Wifi_5G');
insert into rooms values (448,1,2,1,3993,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (449,2,1,3,8681,'Wifi_5G');
insert into rooms values (450,4,1,4,5203,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (451,1,3,1,3912,'Tea set Fireplace coffee_Morning');
insert into rooms values (452,1,1,2,274,'Tea set Fireplace coffee_Morning');
insert into rooms values (453,1,2,5,7418,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (454,4,4,4,4539,'Cushion Wifi_5G coffee Morning');
insert into rooms values (455,1,1,4,3944,'Cushion Wifi_5G coffee Morning');
insert into rooms values (456,3,1,4,9389,'Cushion Wifi_5G coffee Morning');
insert into rooms values (457,2,4,4,3487,'Cushion Wifi_5G coffee Morning');
insert into rooms values (458,3,2,3,6227,'Tea set Fireplace coffee_Morning');
insert into rooms values (459,3,3,1,5989,'Wifi_5G');
insert into rooms values (460,4,1,1,8985,'Cushion Wifi_5G coffee Morning');
insert into rooms values (461,3,2,5,1650,'Tea set Fireplace coffee_Morning');
insert into rooms values (462,2,2,2,862,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (463,3,2,3,4205,'Wifi_5G');
insert into rooms values (464,4,2,3,3861,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (465,3,4,2,8489,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (466,4,3,4,438,'Wifi_5G');
insert into rooms values (467,2,3,4,196,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (468,4,2,5,4454,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (469,1,4,4,6588,'Wifi_5G');
insert into rooms values (470,4,2,1,3859,'Tea set Fireplace coffee_Morning');
insert into rooms values (471,4,2,2,7060,'Tea set Fireplace coffee_Morning');
insert into rooms values (472,4,2,5,5268,'Wifi_5G');
insert into rooms values (473,2,1,1,6270,'Cushion Wifi_5G coffee Morning');
insert into rooms values (474,4,3,1,918,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (475,4,1,4,4742,'Tea set Fireplace coffee_Morning');
insert into rooms values (476,3,1,2,4611,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (477,1,1,4,694,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (478,4,4,5,8497,'Cushion Wifi_5G coffee Morning');
insert into rooms values (479,1,4,4,3388,'Wifi_5G');
insert into rooms values (480,1,2,3,4807,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (481,1,3,1,4021,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (482,1,2,2,2697,'Tea set Fireplace coffee_Morning');
insert into rooms values (483,4,4,3,9124,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (484,4,4,5,3735,'Wifi_5G');
insert into rooms values (485,4,1,1,132,'Wifi_5G');
insert into rooms values (486,1,3,5,4584,'Wifi_5G');
insert into rooms values (487,4,3,3,7337,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (488,4,2,5,6738,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (489,4,1,5,6098,'Tea set Fireplace coffee_Morning');
insert into rooms values (490,1,1,2,1309,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (491,1,2,2,2072,'Wifi_5G');
insert into rooms values (492,4,1,2,7961,'Tea set Fireplace coffee_Morning');
insert into rooms values (493,3,1,4,9620,'Cushion Wifi_5G coffee Morning');
insert into rooms values (494,1,1,2,5428,'Wifi_5G');
insert into rooms values (495,3,1,5,9633,'Cushion Wifi_5G coffee Morning');
insert into rooms values (496,3,2,5,3054,'Tea set Fireplace coffee_Morning');
insert into rooms values (497,3,4,5,7801,'Tea set Fireplace coffee_Morning');
insert into rooms values (498,4,4,2,1021,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (499,4,3,2,399,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (500,2,3,3,4037,'Cushion Television Speaker End_table Tea_setcoffee Morning Wifi_5G Cushion Television Speaker End table Tea set Fireplace Floor lamp Tableet BlindsEnd table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (501,2,2,3,7612,'Tea set Fireplace coffee_Morning');
insert into rooms values (502,2,4,1,9813,'Cushion Wifi_5G coffee Morning');
insert into rooms values (503,3,4,5,9417,'Tea set Fireplace coffee_Morning');
insert into rooms values (504,3,4,4,5015,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (505,3,2,3,2562,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (506,2,3,4,9079,'Cushion Wifi_5G coffee Morning');
insert into rooms values (507,3,3,1,1375,'End table Tea set Fireplace Floor lamp Tableet Blinds');
insert into rooms values (508,1,3,3,8063,'Tea set Fireplace coffee_Morning');


select n from (select count(*) n from rooms);